server:
       port: 8808
       servlet:
               context-path: /v1


spring:
       profiles:
                active: dev
       devtools:
                livereload:
                           enabled: true
       http:
            encoding:
                     charset: UTF-8
                     enabled: true
                     forced: true
                     forced-request: true
                     forced-response: true
       aop:
           auto: true
       aop-proxy-target-class: true                          
         
security:
         user:
              name: pjmall
              password: 1234
         oauth2:     
                client:
                        client-id: pjmall
                        client-secret: 1234