security:
         user:
              name: test
              password: 1234
         oauth2:     
                client:
                        client-id: pjmall
                        client-secret: 1234